FROM golang:1.8.3-alpine

ENV GOPATH /go

RUN mkdir -p "$GOPATH/src/" "$GOPATH/bin" && chmod -R 777 "$GOPATH" && \
    mkdir -p /go/src/github.com/jolestar/go-probe

RUN apk --update add bash git && \
    ln -s /go/src/github.com/jolestar/go-probe /app

WORKDIR /app
